export const PROVIDERS_REQUEST = 'PROVIDERS_REQUEST';
export const PROVIDERS_SUCCESS = 'PROVIDERS_SUCCESS';
export const PROVIDERS_FAILURE = 'PROVIDERS_FAILURE';

export const PROVIDER_DETAILS_REQUEST = 'PROVIDER_DETAILS_REQUEST';
export const PROVIDER_DETAILS_SUCCESS = 'PROVIDER_DETAILS_SUCCESS';
export const PROVIDER_DETAILS_FAILURE = 'PROVIDER_DETAILS_FAILURE';
